export const fantomPools = [
  {
    id: 'fantom-fBEETS',
    logo: 'single-assets/fBEETS.png',
    name: 'fBEETS Compounder',
    token: 'fBEETS',
    tokenDescription: 'fBEETS voting power to vote on CRE8R:FTM Beethoven-X gauge.',
    tokenAddress: '0xfcef8a994209d6916eb2c86cdd2afd60aa6f54b1',
    tokenDecimals: 18,
    tokenDescriptionUrl: '#',
    earnedToken: 'ceazFBEETS',
    earnedTokenAddress: '0x38ceed0dcf80b4794566b31302e8f8863f526012',
    earnContractAddress: '0x38ceed0dcf80b4794566b31302e8f8863f526012',
    pricePerFullShare: 1,
    tvl: 0,
    oracle: 'tokens',
    oracleId: 'fBEETS',
    oraclePrice: 0,
    depositsPaused: false,
    status: 'active',
    platform: 'Beethoven-X',
    assets: ['fBEETS'],
    risks: [
      'COMPLEXITY_LOW',
      'BATTLE_TESTED',
      'IL_NONE',
      'MCAP_MEDIUM',
      'AUDIT',
      'CONTRACTS_VERIFIED',
    ],
    stratType: 'Compounder',
    withdrawalFee: '0.0%',
    buyTokenUrl: 'https://beets.fi/#/stake',
    createdAt: 1622574935,
  },
];
